.__array_struct__
numpy.matlib.float32.__array_wrap__	numpy.generic.__array_wrap__
numpy.matlib.float32.all	numpy.ma.MaskType.all
numpy.matlib.float32.any	numpy.ma.MaskType.any
numpy.matlib.float32.argmax	numpy.ma.MaskType.argmax
numpy.matlib.float32.argmin	numpy.ma.MaskType.argmin
numpy.matlib.float32.argsort	numpy.ma.MaskType.argsort
numpy.matlib.float32.astype	numpy.ma.MaskType.astype
numpy.matlib.float32.base	numpy.ma.MaskType.base
numpy.matlib.float32.byteswap	numpy.ma.MaskType.byteswap
numpy.matlib.float32.choose	numpy.ma.MaskType.choose
numpy.matlib.float32.clip	numpy.ma.MaskType.clip
numpy.matlib.float32.compress	numpy.ma.MaskType.compress
numpy.matlib.float32.conjugate	numpy.ma.MaskType.conjugate
numpy.matlib.float32.copy	numpy.ma.MaskType.copy
numpy.matlib.float32.cumprod	numpy.ma.MaskType.cumprod
numpy.matlib.float32.cumsum	numpy.ma.MaskType.cumsum
numpy.matlib.float32.data	numpy.ma.MaskType.data
numpy.matlib.float32.diagonal	numpy.ma.MaskType.diagonal
numpy.matlib.float32.dtype	numpy.ma.MaskType.dtype
numpy.matlib.float32.dump	numpy.ma.MaskType.dump
numpy.matlib.float32.dumps	numpy.ma.MaskType.dumps
numpy.matlib.float32.fill	numpy.ma.MaskType.fill
numpy.matlib.float32.flags	numpy.ma.MaskType.flags
numpy.matlib.float32.flat	numpy.ma.MaskType.flat
numpy.matlib.float32.flatten	numpy.ma.MaskType.flatten
numpy.matlib.float32.getfield	numpy.ma.MaskType.getfield
numpy.matlib.float32.imag	numpy.ma.MaskType.imag
numpy.matlib.float32.item	numpy.ma.MaskType.item
numpy.matlib.float32.itemset	numpy.ma.MaskType.itemset
numpy.matlib.float32.itemsize	numpy.ma.MaskType.itemsize
numpy.matlib.float32.max	numpy.ma.MaskType.max
numpy.matlib.float32.mean	numpy.ma.MaskType.mean
numpy.matlib.float32.min	numpy.ma.MaskType.min
numpy.matlib.float32.nbytes	numpy.ma.MaskType.nbytes
numpy.matlib.float32.ndim	numpy.ma.MaskType.ndim
numpy.matlib.float32.newbyteorder	numpy.ma.MaskType.newbyteorder
numpy.matlib.float32.nonzero	numpy.ma.MaskType.nonzero
numpy.matlib.float32.prod	numpy.ma.MaskType.prod
numpy.matlib.float32.ptp	numpy.ma.MaskType.ptp
numpy.matlib.float32.put	numpy.ma.MaskType.put
numpy.matlib.float32.ravel	numpy.ma.MaskType.ravel
numpy.matlib.float32.real	numpy.ma.MaskType.real
numpy.matlib.float32.repeat	numpy.ma.MaskType.repeat
numpy.matlib.float32.reshape	numpy.ma.MaskType.reshape
numpy.matlib.float32.resize	numpy.ma.MaskType.resize
numpy.matlib.float32.round	numpy.ma.MaskType.round
numpy.matlib.float32.searchsorted	numpy.ma.MaskType.searchsorted
numpy.matlib.float32.setfield	numpy.ma.MaskType.setfield
numpy.matlib.float32.setflags	numpy.ma.MaskType.setflags
numpy.matlib.float32.shape	numpy.ma.MaskType.shape
numpy.matlib.float32.size	numpy.ma.MaskType.size
numpy.matlib.float32.sort	numpy.ma.MaskType.sort
numpy.matlib.float32.squeeze	numpy.ma.MaskType.squeeze
numpy.matlib.float32.std	numpy.ma.MaskType.std
numpy.matlib.float32.strides	numpy.ma.MaskType.strides
numpy.matlib.float32.sum	numpy.ma.MaskType.sum
numpy.matlib.float32.swapaxes	numpy.ma.MaskType.swapaxes
numpy.matlib.float32.take	numpy.ma.MaskType.take
numpy.matlib.float32.tofile	numpy.ma.MaskType.tofile
numpy.matlib.float32.tolist	numpy.ma.MaskType.tolist
numpy.matlib.float32.tostring	numpy.ma.MaskType.tostring
numpy.matlib.float32.trace	numpy.ma.MaskType.trace
numpy.matlib.float32.transpose	numpy.ma.MaskType.transpose
numpy.matlib.float32.var	numpy.ma.MaskType.var
numpy.matlib.float32.view	numpy.ma.MaskType.view
numpy.matlib.float64.T	numpy.ma.MaskType.T
numpy.matlib.float64.__array__	numpy.generic.__array__
numpy.matlib.float64.__array_interface__	numpy.generic.__array_interface__
numpy.matlib.float64.__array_priority__	numpy.generic.__array_priority__
numpy.matlib.float64.__array_struct__	numpy.generic.__array_struct__
numpy.matlib.float64.__array_wrap__	numpy.generic.__array_wrap__
numpy.matlib.float64.all	numpy.ma.MaskType.all
numpy.matlib.float64.any	numpy.ma.MaskType.any
numpy.matlib.float64.argmax	numpy.ma.MaskType.argmax
numpy.matlib.float64.argmin	numpy.ma.MaskType.argmin
numpy.matlib.float64.argsort	numpy.ma.MaskType.argsort
numpy.matlib.float64.astype	numpy.ma.MaskType.astype
numpy.matlib.float64.base	numpy.ma.MaskType.base
numpy.matlib.float64.byteswap	numpy.ma.MaskType.byteswap
numpy.matlib.float64.choose	numpy.ma.MaskType.choose
numpy.matlib.float64.clip	numpy.ma.MaskType.clip
numpy.matlib.float64.compress	numpy.ma.MaskType.compress
numpy.matlib.float64.conjugate	numpy.ma.MaskType.conjugate
numpy.matlib.float64.copy	numpy.ma.MaskType.copy
numpy.matlib.float64.cumprod	numpy.ma.MaskType.cumprod
numpy.matlib.float64.cumsum	numpy.ma.MaskType.cumsum
numpy.matlib.float64.data	numpy.ma.MaskType.data
numpy.matlib.float64.diagonal	numpy.ma.MaskType.diagonal
numpy.matlib.float64.dtype	numpy.ma.MaskType.dtype
numpy.matlib.float64.dump	numpy.ma.MaskType.dump
numpy.matlib.float64.dumps	numpy.ma.MaskType.dumps
numpy.matlib.float64.fill	numpy.ma.MaskType.fill
numpy.matlib.float64.flags	numpy.ma.MaskType.flags
numpy.matlib.float64.flat	numpy.ma.MaskType.flat
numpy.matlib.float64.flatten	numpy.ma.MaskType.flatten
numpy.matlib.float64.getfield	numpy.ma.MaskType.getfield
numpy.matlib.float64.imag	numpy.ma.MaskType.imag
numpy.matlib.float64.item	numpy.ma.MaskType.item
numpy.matlib.float64.itemset	numpy.ma.MaskType.itemset
numpy.matlib.float64.itemsize	numpy.ma.MaskType.itemsize
numpy.matlib.float64.max	numpy.ma.MaskType.max
numpy.matlib.float64.mean	numpy.ma.MaskType.mean
numpy.matlib.float64.min	numpy.ma.MaskType.min
numpy.matlib.float64.nbytes	numpy.ma.MaskType.nbytes
numpy.matlib.float64.ndim	numpy.ma.MaskType.ndim
numpy.matlib.float64.newbyteorder	numpy.ma.MaskType.newbyteorder
numpy.matlib.float64.nonzero	numpy.ma.MaskType.nonzero
numpy.matlib.float64.prod	numpy.ma.MaskType.prod
numpy.matlib.float64.ptp	numpy.ma.MaskType.ptp
numpy.matlib.float64.put	numpy.ma.MaskType.put
numpy.matlib.float64.ravel	numpy.ma.MaskType.ravel
numpy.matlib.float64.real	numpy.ma.MaskType.real
numpy.matlib.float64.repeat	numpy.ma.MaskType.repeat
numpy.matlib.float64.reshape	numpy.ma.MaskType.reshape
numpy.matlib.float64.resize	numpy.ma.MaskType.resize
numpy.matlib.float64.round	numpy.ma.MaskType.round
numpy.matlib.float64.searchsorted	numpy.ma.MaskType.searchsorted
numpy.matlib.float64.setfield	numpy.ma.MaskType.setfield
numpy.matlib.float64.setflags	numpy.ma.MaskType.setflags
numpy.matlib.float64.shape	numpy.ma.MaskType.shape
numpy.matlib.float64.size	numpy.ma.MaskType.size
numpy.matlib.float64.sort	numpy.ma.MaskType.sort
numpy.matlib.float64.squeeze	numpy.ma.MaskType.squeeze
numpy.matlib.float64.std	numpy.ma.MaskType.std
numpy.matlib.float64.strides	numpy.ma.MaskType.strides
numpy.matlib.float64.sum	numpy.ma.MaskType.sum
numpy.matlib.float64.swapaxes	numpy.ma.MaskType.swapaxes
numpy.matlib.float64.take	numpy.ma.MaskType.take
numpy.matlib.float64.tofile	numpy.ma.MaskType.tofile
numpy.matlib.float64.tolist	numpy.ma.MaskType.tolist
numpy.matlib.float64.tostring	numpy.ma.MaskType.tostring
numpy.matlib.float64.trace	numpy.ma.MaskType.trace
numpy.matlib.float64.transpose	numpy.ma.MaskType.transpose
numpy.matlib.float64.var	numpy.ma.MaskType.var
numpy.matlib.float64.view	numpy.ma.MaskType.view
numpy.matlib.float_.T	numpy.ma.MaskType.T
numpy.matlib.float_.__array__	numpy.generic.__array__
numpy.matlib.float_.__array_interface__	numpy.generic.__array_interface__
numpy.matlib.float_.__array_priority__	numpy.generic.__array_priority__
numpy.matlib.float_.__array_struct__	numpy.generic.__array_struct__
numpy.matlib.float_.__array_wrap__	numpy.generic.__array_wrap__
numpy.matlib.float_.all	numpy.ma.MaskType.all
numpy.matlib.float_.any	numpy.ma.MaskType.any
numpy.matlib.float_.argmax	numpy.ma.MaskType.argmax
numpy.matlib.float_.argmin	numpy.ma.MaskType.argmin
numpy.matlib.float_.argsort	numpy.ma.MaskType.argsort
numpy.matlib.float_.astype	numpy.ma.MaskType.astype
numpy.matlib.float_.base	numpy.ma.MaskType.base
numpy.matlib.float_.byteswap	numpy.ma.MaskType.byteswap
numpy.matlib.float_.choose	numpy.ma.MaskType.choose
numpy.matlib.float_.clip	numpy.ma.MaskType.clip
numpy.matlib.float_.compress	numpy.ma.MaskType.compress
numpy.matlib.float_.conjugate	numpy.ma.MaskType.conjugate
numpy.matlib.float_.copy	numpy.ma.MaskType.copy
numpy.matlib.float_.cumprod	numpy.ma.MaskType.cumprod
numpy.matlib.float_.cumsum	numpy.ma.MaskType.cumsum
numpy.matlib.float_.data	numpy.ma.MaskType.data
numpy.matlib.float_.diagonal	numpy.ma.MaskType.diagonal
numpy.matlib.float_.dtype	numpy.ma.MaskType.dtype
numpy.matlib.float_.dump	numpy.ma.MaskType.dump
numpy.matlib.float_.dumps	numpy.ma.MaskType.dumps
numpy.matlib.float_.fill	numpy.ma.MaskType.fill
numpy.matlib.float_.flags	numpy.ma.MaskType.flags
numpy.matlib.float_.flat	numpy.ma.MaskType.flat
numpy.matlib.float_.flatten	numpy.ma.MaskType.flatten
numpy.matlib.float_.getfield	numpy.ma.MaskType.getfield
numpy.matlib.float_.imag	numpy.ma.MaskType.imag
numpy.matlib.float_.item	numpy.ma.MaskType.item
numpy.matlib.float_.itemset	numpy.ma.MaskType.itemset
numpy.matlib.float_.itemsize	numpy.ma.MaskType.itemsize
numpy.matlib.float_.max	numpy.ma.MaskType.max
numpy.matlib.float_.mean	numpy.ma.MaskType.mean
numpy.matlib.float_.min	numpy.ma.MaskType.min
numpy.matlib.float_.nbytes	numpy.ma.MaskType.nbytes
numpy.matlib.float_.ndim	numpy.ma.MaskType.ndim
numpy.matlib.float_.newbyteorder	numpy.ma.MaskType.newbyteorder
numpy.matlib.float_.nonzero	numpy.ma.MaskType.nonzero
numpy.matlib.float_.prod	numpy.ma.MaskType.prod
numpy.matlib.float_.ptp	numpy.ma.MaskType.ptp
numpy.matlib.float_.put	numpy.ma.MaskType.put
numpy.matlib.float_.ravel	numpy.ma.MaskType.ravel
numpy.matlib.float_.real	numpy.ma.MaskType.real
numpy.matlib.float_.repeat	numpy.ma.MaskType.repeat
numpy.matlib.float_.reshape	numpy.ma.MaskType.reshape
numpy.matlib.float_.resize	numpy.ma.MaskType.resize
numpy.matlib.float_.round	numpy.ma.MaskType.round
numpy.matlib.float_.searchsorted	numpy.ma.MaskType.searchsorted
numpy.matlib.float_.setfield	numpy.ma.MaskType.setfield
numpy.matlib.float_.setflags	numpy.ma.MaskType.setflags
numpy.matlib.float_.shape	numpy.ma.MaskType.shape
numpy.matlib.float_.size	numpy.ma.MaskType.size
numpy.matlib.float_.sort	numpy.ma.MaskType.sort
numpy.matlib.float_.squeeze	numpy.ma.MaskType.squeeze
numpy.matlib.float_.std	numpy.ma.MaskType.std
numpy.matlib.float_.strides	numpy.ma.MaskType.strides
numpy.matlib.float_.sum	numpy.ma.MaskType.sum
numpy.matlib.float_.swapaxes	numpy.ma.MaskType.swapaxes
numpy.matlib.float_.take	numpy.ma.MaskType.take
numpy.matlib.float_.tofile	numpy.ma.MaskType.tofile
numpy.matlib.float_.tolist	numpy.ma.MaskType.tolist
numpy.matlib.float_.tostring	numpy.ma.MaskType.tostring
numpy.matlib.float_.trace	numpy.ma.MaskType.trace
numpy.matlib.float_.transpose	numpy.ma.MaskType.transpose
numpy.matlib.float_.var	numpy.ma.MaskType.var
numpy.matlib.float_.view	numpy.ma.MaskType.view
numpy.matlib.float_power	numpy.float_power
numpy.matlib.floating.T	numpy.ma.MaskType.T
numpy.matlib.floating.__array__	numpy.generic.__array__
numpy.matl