="ADCMP0ENL" settingAlias="CMPEN9" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="BTWN" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="BTWN" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN0"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN1"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN10"/>
         <value>10</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN11"/>
         <value>11</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN12"/>
         <value>12</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN13"/>
         <value>13</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN14"/>
         <value>14</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN15"/>
         <value>15</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN16"/>
         <value>16</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN17"/>
         <value>17</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAlias="CHNL" alias="AN18"/>
         <value>18</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="ADC1" registerAlias="ADCMP1CON" settingAl