ore.tokenManager.SettingKey" moduleName="TMR1" registerAlias="TMR" settingAlias="TMR"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="AllInterrupts"/>
         <value>enabled</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="BaudRate"/>
         <value>9600</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="BaudRateError"/>
         <value>0.160</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="DataBits"/>
         <value>8</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="FlowControl"/>
         <value>None</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="InternalClock"/>
         <value>4000000</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="Parity"/>
         <value>None</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="RedirectPrintf"/>
         <value>enabled</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="SWRXBufferSize"/>
         <value>8</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="SWTXBufferSize"/>
         <value>254</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="UART1_UEIISRFunction"/>
         <value>ISR_UART1_UEI</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="UART1_UEVTIISRFunction"/>
         <value>ISR_UART1_UEVTI</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="UART1_URXIISRFunction"/>
         <value>ISR_UART1_URXI</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="UART1_UTXIISRFunction"/>
         <value>ISR_UART1_UTXI</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="UARTFunctionMode"/>
         <value>UART</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.CustomKey" moduleName="UART1" name="inputmode"/>
         <value>easysetup</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="UART1" registerAlias="