ey class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E4" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E5" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E5" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E6" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E6" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E7" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E7" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E8" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E8" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E9" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNEN1E" settingAlias="CNIE1E9" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA0" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA0" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA1" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA1" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA2" alias="disabled"/>
         <value>0</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core.tokenManager.OptionKey" moduleName="Pin Module" registerAlias="CNFA" settingAlias="CNFA2" alias="enabled"/>
         <value>1</value>
      </entry>
      <entry>
         <key class="com.microchip.mcc.core